services:
  db:
    image: ghcr.io/baosystems/postgis:17-3.5
    container_name: osm_mappers_db
    restart: always
    environment:
      POSTGRES_USER: osm_user
      POSTGRES_PASSWORD: osm_pass
      POSTGRES_DB: osm_db
    volumes:
      - /tmp/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U osm_user -d osm_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Migration container using Alembic to upgrade schema.
  migrate:
    build: .
    container_name: osm_mappers_migrate
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: osm_user
      POSTGRES_PASSWORD: osm_pass
      POSTGRES_DB: osm_db
    # Override the default CMD to run the Alembic migration.
    command: alembic upgrade head

  # Archive loader service.
  loader:
    build: .
    container_name: osm_mappers_archive_loader
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_healthy
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: osm_user
      POSTGRES_PASSWORD: osm_pass
      POSTGRES_DB: osm_db
    volumes:
      - ./data:/data
    # Use a custom entrypoint script for the loader.
    entrypoint: ["/app/scripts/archive_loader_entrypoint.sh"]

  # Main FastAPI application.
  app:
    build: .
    container_name: osm_mappers_app
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: osm_user
      POSTGRES_PASSWORD: osm_pass
      POSTGRES_DB: osm_db
      PORT: 8000
    command: /bin/sh -c "/app/scripts/init_db.sh && osm-meet-your-mappers --host 0.0.0.0 --port 8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Continuous backfill service.
  backfill:
    build: .
    container_name: osm_mappers_backfill
    depends_on:
      db:
        condition: service_healthy
      app:
        condition: service_healthy
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: osm_user
      POSTGRES_PASSWORD: osm_pass
      POSTGRES_DB: osm_db
      MIN_SEQ: 0
      BATCH_SIZE: 50000
      BLOCK_SIZE: 10
      SLEEP_TIME: 300
    command: ["python", "-u", "scripts/backfill.py"]
