version: '3.8'

services:
  db:
    image: ghcr.io/baosystems/postgis:17-3.5
    container_name: osm_mappers_db
    restart: always
    environment:
      POSTGRES_USER: osm_user
      POSTGRES_PASSWORD: osm_pass
      POSTGRES_DB: osm_db
    volumes:
      - /tmp/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U osm_user -d osm_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  loader:
    build: .
    container_name: osm_mappers_loader
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: osm_user
      POSTGRES_PASSWORD: osm_pass
      POSTGRES_DB: osm_db
    volumes:
      - ${OSM_FILE_PATH}:/data/changesets.osm.bz2
    command: python /app/scripts/archive_loader.py /data/changesets.osm.bz2

volumes:
  db_data:
