services:
  db:
    image: ghcr.io/baosystems/postgis:17
    volumes:
      - /tmp/postgresql/data:/var/lib/postgresql/data
      - ./scripts/setup_db.sql:/docker-entrypoint-initdb.d/setup_db.sql
    ports:
      - "5432:5432"
    env_file:
      - .env
    # environment:
    #   - PYTHONPATH=/app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U osmuser -d osm_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    command: uvicorn osm_meet_your_mappers.api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  backfill:
    build: .
    working_dir: /app
    command: python -m scripts.backfill
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
