services:
  db:
    image: ghcr.io/baosystems/postgis:17
    volumes:
      - /tmp/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  api:
    build: .
    command: uvicorn osm_meet_your_mappers.api:main --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  backfill:
    build: .
    command: python scripts/backfill.py
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
