[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "osm-meet-your-mappers"
version = "1.0.0"
description = "Meet the OpenStreetMap mappers in your area"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
authors = [
    {name = "Martijn van Exel", email = "m@rtijn.org"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "fastapi>=0.95.0",
    "uvicorn>=0.21.0",
    "sqlalchemy>=2.0.0",
    "psycopg2-binary>=2.9.0",
    "requests>=2.28.0",
    "pydantic>=2.0.0",
    "sqlalchemy-utils>=0.41.0",
    "geoalchemy2==0.17.0",
    "shapely==2.0.7",
    "pyyaml==6.0.2",
    "lxml==5.3.1"
]

[project.scripts]
osm-meet-your-mappers = "osm_meet_your_mappers.api:main"
osm-meet-your-mappers-rebuild-db = "osm_meet_your_mappers.db:rebuild_database"
osm-meet-your-mappers-backfill = "scripts.backfill:main"
osm-meet-your-mappers-init-db = "osm_meet_your_mappers.db:init_database"
osm-meet-your-mappers-create-tables = "osm_meet_your_mappers.db:create_tables"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
osm_meet_your_mappers = [
    "static/*"
]
