[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "osm-changeset-loader"
version = "0.1.0"
description = "OpenStreetMap changeset loader and API"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
authors = [
    {name = "Martijn van Exel", email = "m@rtijn.org"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "fastapi>=0.95.0",
    "uvicorn>=0.21.0",
    "sqlalchemy>=2.0.0",
    "psycopg2-binary>=2.9.0",
    "requests>=2.28.0",
    "pydantic>=2.0.0",
    "sqlalchemy-utils>=0.41.0",
]

[project.scripts]
osm-changeset-loader = "osm_changeset_loader.api:main"
osm-changeset-catchup = "catch_up.py:main"
osm-changeset-rebuild-db = "osm_changeset_loader.db:rebuild_database"

[tool.setuptools.packages.find]
where = ["osm_changeset_loader"]
